### ISSUE TITLE
Module not imported in swift 3.0.2

### ISSUE THREAD

**Issue by andre991** [izouxv/SwiftyDB#2]
Module compiled with Swift 3.0 cannot be imported in Swift 3.0.2
![captura de tela 2017-02-13 as 17 17 38](https://cloud.githubusercontent.com/assets/8302454/22899017/7c79bf1e-f210-11e6-89e0-4b7b9edc800c.png)

**Comment by izouxv** [comment]
you can complied again with carthage

**Comment by andre991** [comment]
I try but it not working. 
<img width="580" alt="captura de tela 2017-02-14 as 08 27 19" src="https://cloud.githubusercontent.com/assets/8302454/22925365/8f4c92ea-f28f-11e6-8649-60880cbd8597.png">

**Comment by izouxv** [comment]
try catool to build , carthage build error, catool is correct
![screen shot 2017-02-15 at 14 56 31](https://cloud.githubusercontent.com/assets/1646763/22963653/115f4ffc-f38f-11e6-9c7d-dc4c7ba28eae.png)

**Comment by izouxv** [comment]
fix the bug
